# TCL File Generated by Component Editor 17.1
# Thu Jun 27 20:13:22 CST 2019
# DO NOT MODIFY


# 
# Ir_HT6221_Decode_Irq "Ir_HT6221_Decode_Irq" v1.0
# lsj 2019.06.27.20:13:22
# ir decoder which can produce irq
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module Ir_HT6221_Decode_Irq
# 
set_module_property DESCRIPTION "ir decoder which can produce irq"
set_module_property NAME Ir_HT6221_Decode_Irq
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP lsj_ip
set_module_property AUTHOR lsj
set_module_property DISPLAY_NAME Ir_HT6221_Decode_Irq
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Ir_HT6221_Decode_Irq
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file Ir_HT6221_Decode_Irq.v VERILOG PATH Ir_HT6221_Decode_Irq.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter T_Sa_Clk INTEGER 10000
set_parameter_property T_Sa_Clk DEFAULT_VALUE 10000
set_parameter_property T_Sa_Clk DISPLAY_NAME T_Sa_Clk
set_parameter_property T_Sa_Clk TYPE INTEGER
set_parameter_property T_Sa_Clk UNITS None
set_parameter_property T_Sa_Clk ALLOWED_RANGES -2147483648:2147483647
set_parameter_property T_Sa_Clk HDL_PARAMETER true
add_parameter T_Clk50m INTEGER 20
set_parameter_property T_Clk50m DEFAULT_VALUE 20
set_parameter_property T_Clk50m DISPLAY_NAME T_Clk50m
set_parameter_property T_Clk50m TYPE INTEGER
set_parameter_property T_Clk50m UNITS None
set_parameter_property T_Clk50m ALLOWED_RANGES -2147483648:2147483647
set_parameter_property T_Clk50m HDL_PARAMETER true
add_parameter N_Code INTEGER 32
set_parameter_property N_Code DEFAULT_VALUE 32
set_parameter_property N_Code DISPLAY_NAME N_Code
set_parameter_property N_Code TYPE INTEGER
set_parameter_property N_Code UNITS None
set_parameter_property N_Code ALLOWED_RANGES -2147483648:2147483647
set_parameter_property N_Code HDL_PARAMETER true
add_parameter N_Dev INTEGER 20
set_parameter_property N_Dev DEFAULT_VALUE 20
set_parameter_property N_Dev DISPLAY_NAME N_Dev
set_parameter_property N_Dev TYPE INTEGER
set_parameter_property N_Dev UNITS None
set_parameter_property N_Dev ALLOWED_RANGES -2147483648:2147483647
set_parameter_property N_Dev HDL_PARAMETER true


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock_sink
set_interface_property reset synchronousEdges NONE
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clk50m clk Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock_sink
set_interface_property conduit_end associatedReset reset
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end clk100k clk100k Output 1
add_interface_port conduit_end decode_ok decode_ok Output 1
add_interface_port conduit_end decoding decoding Output 1
add_interface_port conduit_end error error Output 1
add_interface_port conduit_end ir_Data ir_data Output 8
add_interface_port conduit_end ir_AddrH ir_addrh Output 8
add_interface_port conduit_end ir_AddrL ir_addrl Output 8
add_interface_port conduit_end ir_in ir_in Input 1
add_interface_port conduit_end ir_out ir_out Output 32


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint as
set_interface_property interrupt_sender associatedClock clock_sink
set_interface_property interrupt_sender associatedReset reset
set_interface_property interrupt_sender bridgedReceiverOffset 0
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender irq_out irq Output 1


# 
# connection point as
# 
add_interface as avalon end
set_interface_property as addressUnits WORDS
set_interface_property as associatedClock clock_sink
set_interface_property as associatedReset reset
set_interface_property as bitsPerSymbol 8
set_interface_property as burstOnBurstBoundariesOnly false
set_interface_property as burstcountUnits WORDS
set_interface_property as explicitAddressSpan 0
set_interface_property as holdTime 0
set_interface_property as linewrapBursts false
set_interface_property as maximumPendingReadTransactions 0
set_interface_property as maximumPendingWriteTransactions 0
set_interface_property as readLatency 0
set_interface_property as readWaitTime 1
set_interface_property as setupTime 0
set_interface_property as timingUnits Cycles
set_interface_property as writeWaitTime 0
set_interface_property as ENABLED true
set_interface_property as EXPORT_OF ""
set_interface_property as PORT_NAME_MAP ""
set_interface_property as CMSIS_SVD_VARIABLES ""
set_interface_property as SVD_ADDRESS_GROUP ""

add_interface_port as CPU_CS chipselect Input 1
add_interface_port as CPU_RD read Input 1
add_interface_port as CPU_WR write Input 1
add_interface_port as CPU_Addr address Input 1
add_interface_port as CPU_RD_Data readdata Output 32
add_interface_port as CPU_WR_Data writedata Input 32
set_interface_assignment as embeddedsw.configuration.isFlash 0
set_interface_assignment as embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment as embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment as embeddedsw.configuration.isPrintableDevice 0

