	mysystem u0 (
		.btn_export           (<connected-to-btn_export>),           //          btn.export
		.clk_clk              (<connected-to-clk_clk>),              //          clk.clk
		.clk20m_clk           (<connected-to-clk20m_clk>),           //       clk20m.clk
		.epcs_dclk            (<connected-to-epcs_dclk>),            //         epcs.dclk
		.epcs_sce             (<connected-to-epcs_sce>),             //             .sce
		.epcs_sdo             (<connected-to-epcs_sdo>),             //             .sdo
		.epcs_data0           (<connected-to-epcs_data0>),           //             .data0
		.ir_decoder_clk100k   (<connected-to-ir_decoder_clk100k>),   //   ir_decoder.clk100k
		.ir_decoder_decode_ok (<connected-to-ir_decoder_decode_ok>), //             .decode_ok
		.ir_decoder_decoding  (<connected-to-ir_decoder_decoding>),  //             .decoding
		.ir_decoder_error     (<connected-to-ir_decoder_error>),     //             .error
		.ir_decoder_ir_data   (<connected-to-ir_decoder_ir_data>),   //             .ir_data
		.ir_decoder_ir_addrh  (<connected-to-ir_decoder_ir_addrh>),  //             .ir_addrh
		.ir_decoder_ir_addrl  (<connected-to-ir_decoder_ir_addrl>),  //             .ir_addrl
		.ir_decoder_ir_in     (<connected-to-ir_decoder_ir_in>),     //             .ir_in
		.ir_decoder_ir_out    (<connected-to-ir_decoder_ir_out>),    //             .ir_out
		.lcd_wr_n             (<connected-to-lcd_wr_n>),             //          lcd.wr_n
		.lcd_rd_n             (<connected-to-lcd_rd_n>),             //             .rd_n
		.lcd_data             (<connected-to-lcd_data>),             //             .data
		.lcd_rs               (<connected-to-lcd_rs>),               //             .rs
		.lcd_cs_n             (<connected-to-lcd_cs_n>),             //             .cs_n
		.lcd_bl_export        (<connected-to-lcd_bl_export>),        //       lcd_bl.export
		.lcd_rst_export       (<connected-to-lcd_rst_export>),       //      lcd_rst.export
		.meiled_export        (<connected-to-meiled_export>),        //       meiled.export
		.meisw_export         (<connected-to-meisw_export>),         //        meisw.export
		.mul_export           (<connected-to-mul_export>),           //          mul.export
		.pio0_inc_export      (<connected-to-pio0_inc_export>),      //     pio0_inc.export
		.reset_reset_n        (<connected-to-reset_reset_n>),        //        reset.reset_n
		.sdram_addr           (<connected-to-sdram_addr>),           //        sdram.addr
		.sdram_ba             (<connected-to-sdram_ba>),             //             .ba
		.sdram_cas_n          (<connected-to-sdram_cas_n>),          //             .cas_n
		.sdram_cke            (<connected-to-sdram_cke>),            //             .cke
		.sdram_cs_n           (<connected-to-sdram_cs_n>),           //             .cs_n
		.sdram_dq             (<connected-to-sdram_dq>),             //             .dq
		.sdram_dqm            (<connected-to-sdram_dqm>),            //             .dqm
		.sdram_ras_n          (<connected-to-sdram_ras_n>),          //             .ras_n
		.sdram_we_n           (<connected-to-sdram_we_n>),           //             .we_n
		.sdram_clk_clk        (<connected-to-sdram_clk_clk>),        //    sdram_clk.clk
		.uart_0_rxd           (<connected-to-uart_0_rxd>),           //       uart_0.rxd
		.uart_0_txd           (<connected-to-uart_0_txd>),           //             .txd
		.vpp_adc0_export      (<connected-to-vpp_adc0_export>),      //     vpp_adc0.export
		.vpp_adc1_export      (<connected-to-vpp_adc1_export>),      //     vpp_adc1.export
		.filter_work_export   (<connected-to-filter_work_export>),   //  filter_work.export
		.filter_addr_export   (<connected-to-filter_addr_export>),   //  filter_addr.export
		.filter_data_export   (<connected-to-filter_data_export>),   //  filter_data.export
		.filter_write_export  (<connected-to-filter_write_export>)   // filter_write.export
	);

