// mysystem.v

// Generated using ACDS version 17.1 590

`timescale 1 ps / 1 ps
module mysystem (
		input  wire [1:0]  btn_export,           //          btn.export
		input  wire        clk_clk,              //          clk.clk
		output wire        clk20m_clk,           //       clk20m.clk
		output wire        epcs_dclk,            //         epcs.dclk
		output wire        epcs_sce,             //             .sce
		output wire        epcs_sdo,             //             .sdo
		input  wire        epcs_data0,           //             .data0
		output wire [4:0]  filter_addr_export,   //  filter_addr.export
		output wire [9:0]  filter_data_export,   //  filter_data.export
		output wire        filter_work_export,   //  filter_work.export
		output wire        filter_write_export,  // filter_write.export
		output wire        ir_decoder_clk100k,   //   ir_decoder.clk100k
		output wire        ir_decoder_decode_ok, //             .decode_ok
		output wire        ir_decoder_decoding,  //             .decoding
		output wire        ir_decoder_error,     //             .error
		output wire [7:0]  ir_decoder_ir_data,   //             .ir_data
		output wire [7:0]  ir_decoder_ir_addrh,  //             .ir_addrh
		output wire [7:0]  ir_decoder_ir_addrl,  //             .ir_addrl
		input  wire        ir_decoder_ir_in,     //             .ir_in
		output wire [31:0] ir_decoder_ir_out,    //             .ir_out
		output wire        lcd_wr_n,             //          lcd.wr_n
		output wire        lcd_rd_n,             //             .rd_n
		inout  wire [15:0] lcd_data,             //             .data
		output wire        lcd_rs,               //             .rs
		output wire        lcd_cs_n,             //             .cs_n
		output wire        lcd_bl_export,        //       lcd_bl.export
		output wire        lcd_rst_export,       //      lcd_rst.export
		output wire [7:0]  meiled_export,        //       meiled.export
		input  wire [7:0]  meisw_export,         //        meisw.export
		output wire [7:0]  mul_export,           //          mul.export
		output wire [31:0] pio0_inc_export,      //     pio0_inc.export
		input  wire        reset_reset_n,        //        reset.reset_n
		output wire [11:0] sdram_addr,           //        sdram.addr
		output wire [1:0]  sdram_ba,             //             .ba
		output wire        sdram_cas_n,          //             .cas_n
		output wire        sdram_cke,            //             .cke
		output wire        sdram_cs_n,           //             .cs_n
		inout  wire [15:0] sdram_dq,             //             .dq
		output wire [1:0]  sdram_dqm,            //             .dqm
		output wire        sdram_ras_n,          //             .ras_n
		output wire        sdram_we_n,           //             .we_n
		output wire        sdram_clk_clk,        //    sdram_clk.clk
		input  wire        uart_0_rxd,           //       uart_0.rxd
		output wire        uart_0_txd,           //             .txd
		input  wire [7:0]  vpp_adc0_export,      //     vpp_adc0.export
		input  wire [7:0]  vpp_adc1_export       //     vpp_adc1.export
	);

	wire         altpll_0_c0_clk;                                             // altpll_0:c0 -> [Ir_HT6221_Decode_Irq_0:clk50m, epcs:clk, irq_mapper:clk, jtag_uart_0:clk, lcd:clk, lcd_bl:clk, lcd_rst:clk, mm_interconnect_0:altpll_0_c0_clk, nios2:clk, pio0_inc:clk, pio10_filter_write:clk, pio1_sw:clk, pio2_led:clk, pio3_btn:clk, pio4_vpp_adc1:clk, pio5_vpp_adc0:clk, pio6_mul:clk, pio7_filter_work:clk, pio8_filter_addr:clk, pio9_filter_data:clk, rst_controller_001:clk, rst_controller_002:clk, sdram:clk, uart_0:clk]
	wire  [31:0] nios2_data_master_readdata;                                  // mm_interconnect_0:nios2_data_master_readdata -> nios2:d_readdata
	wire         nios2_data_master_waitrequest;                               // mm_interconnect_0:nios2_data_master_waitrequest -> nios2:d_waitrequest
	wire         nios2_data_master_debugaccess;                               // nios2:debug_mem_slave_debugaccess_to_roms -> mm_interconnect_0:nios2_data_master_debugaccess
	wire  [24:0] nios2_data_master_address;                                   // nios2:d_address -> mm_interconnect_0:nios2_data_master_address
	wire   [3:0] nios2_data_master_byteenable;                                // nios2:d_byteenable -> mm_interconnect_0:nios2_data_master_byteenable
	wire         nios2_data_master_read;                                      // nios2:d_read -> mm_interconnect_0:nios2_data_master_read
	wire         nios2_data_master_readdatavalid;                             // mm_interconnect_0:nios2_data_master_readdatavalid -> nios2:d_readdatavalid
	wire         nios2_data_master_write;                                     // nios2:d_write -> mm_interconnect_0:nios2_data_master_write
	wire  [31:0] nios2_data_master_writedata;                                 // nios2:d_writedata -> mm_interconnect_0:nios2_data_master_writedata
	wire  [31:0] nios2_instruction_master_readdata;                           // mm_interconnect_0:nios2_instruction_master_readdata -> nios2:i_readdata
	wire         nios2_instruction_master_waitrequest;                        // mm_interconnect_0:nios2_instruction_master_waitrequest -> nios2:i_waitrequest
	wire  [24:0] nios2_instruction_master_address;                            // nios2:i_address -> mm_interconnect_0:nios2_instruction_master_address
	wire         nios2_instruction_master_read;                               // nios2:i_read -> mm_interconnect_0:nios2_instruction_master_read
	wire         nios2_instruction_master_readdatavalid;                      // mm_interconnect_0:nios2_instruction_master_readdatavalid -> nios2:i_readdatavalid
	wire         mm_interconnect_0_ir_ht6221_decode_irq_0_as_chipselect;      // mm_interconnect_0:Ir_HT6221_Decode_Irq_0_as_chipselect -> Ir_HT6221_Decode_Irq_0:CPU_CS
	wire  [31:0] mm_interconnect_0_ir_ht6221_decode_irq_0_as_readdata;        // Ir_HT6221_Decode_Irq_0:CPU_RD_Data -> mm_interconnect_0:Ir_HT6221_Decode_Irq_0_as_readdata
	wire   [0:0] mm_interconnect_0_ir_ht6221_decode_irq_0_as_address;         // mm_interconnect_0:Ir_HT6221_Decode_Irq_0_as_address -> Ir_HT6221_Decode_Irq_0:CPU_Addr
	wire         mm_interconnect_0_ir_ht6221_decode_irq_0_as_read;            // mm_interconnect_0:Ir_HT6221_Decode_Irq_0_as_read -> Ir_HT6221_Decode_Irq_0:CPU_RD
	wire         mm_interconnect_0_ir_ht6221_decode_irq_0_as_write;           // mm_interconnect_0:Ir_HT6221_Decode_Irq_0_as_write -> Ir_HT6221_Decode_Irq_0:CPU_WR
	wire  [31:0] mm_interconnect_0_ir_ht6221_decode_irq_0_as_writedata;       // mm_interconnect_0:Ir_HT6221_Decode_Irq_0_as_writedata -> Ir_HT6221_Decode_Irq_0:CPU_WR_Data
	wire         mm_interconnect_0_lcd_av_chipselect;                         // mm_interconnect_0:lcd_av_chipselect -> lcd:av_chipselect_n
	wire  [15:0] mm_interconnect_0_lcd_av_readdata;                           // lcd:av_readdata -> mm_interconnect_0:lcd_av_readdata
	wire   [0:0] mm_interconnect_0_lcd_av_address;                            // mm_interconnect_0:lcd_av_address -> lcd:av_addr
	wire         mm_interconnect_0_lcd_av_read;                               // mm_interconnect_0:lcd_av_read -> lcd:av_read_n
	wire         mm_interconnect_0_lcd_av_write;                              // mm_interconnect_0:lcd_av_write -> lcd:av_write_n
	wire  [15:0] mm_interconnect_0_lcd_av_writedata;                          // mm_interconnect_0:lcd_av_writedata -> lcd:av_writedata
	wire         mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_chipselect;  // mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_chipselect -> jtag_uart_0:av_chipselect
	wire  [31:0] mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_readdata;    // jtag_uart_0:av_readdata -> mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_readdata
	wire         mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_waitrequest; // jtag_uart_0:av_waitrequest -> mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_waitrequest
	wire   [0:0] mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_address;     // mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_address -> jtag_uart_0:av_address
	wire         mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_read;        // mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_read -> jtag_uart_0:av_read_n
	wire         mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_write;       // mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_write -> jtag_uart_0:av_write_n
	wire  [31:0] mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_writedata;   // mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_writedata -> jtag_uart_0:av_writedata
	wire  [31:0] mm_interconnect_0_nios2_debug_mem_slave_readdata;            // nios2:debug_mem_slave_readdata -> mm_interconnect_0:nios2_debug_mem_slave_readdata
	wire         mm_interconnect_0_nios2_debug_mem_slave_waitrequest;         // nios2:debug_mem_slave_waitrequest -> mm_interconnect_0:nios2_debug_mem_slave_waitrequest
	wire         mm_interconnect_0_nios2_debug_mem_slave_debugaccess;         // mm_interconnect_0:nios2_debug_mem_slave_debugaccess -> nios2:debug_mem_slave_debugaccess
	wire   [8:0] mm_interconnect_0_nios2_debug_mem_slave_address;             // mm_interconnect_0:nios2_debug_mem_slave_address -> nios2:debug_mem_slave_address
	wire         mm_interconnect_0_nios2_debug_mem_slave_read;                // mm_interconnect_0:nios2_debug_mem_slave_read -> nios2:debug_mem_slave_read
	wire   [3:0] mm_interconnect_0_nios2_debug_mem_slave_byteenable;          // mm_interconnect_0:nios2_debug_mem_slave_byteenable -> nios2:debug_mem_slave_byteenable
	wire         mm_interconnect_0_nios2_debug_mem_slave_write;               // mm_interconnect_0:nios2_debug_mem_slave_write -> nios2:debug_mem_slave_write
	wire  [31:0] mm_interconnect_0_nios2_debug_mem_slave_writedata;           // mm_interconnect_0:nios2_debug_mem_slave_writedata -> nios2:debug_mem_slave_writedata
	wire         mm_interconnect_0_epcs_epcs_control_port_chipselect;         // mm_interconnect_0:epcs_epcs_control_port_chipselect -> epcs:chipselect
	wire  [31:0] mm_interconnect_0_epcs_epcs_control_port_readdata;           // epcs:readdata -> mm_interconnect_0:epcs_epcs_control_port_readdata
	wire   [8:0] mm_interconnect_0_epcs_epcs_control_port_address;            // mm_interconnect_0:epcs_epcs_control_port_address -> epcs:address
	wire         mm_interconnect_0_epcs_epcs_control_port_read;               // mm_interconnect_0:epcs_epcs_control_port_read -> epcs:read_n
	wire         mm_interconnect_0_epcs_epcs_control_port_write;              // mm_interconnect_0:epcs_epcs_control_port_write -> epcs:write_n
	wire  [31:0] mm_interconnect_0_epcs_epcs_control_port_writedata;          // mm_interconnect_0:epcs_epcs_control_port_writedata -> epcs:writedata
	wire  [31:0] mm_interconnect_0_altpll_0_pll_slave_readdata;               // altpll_0:readdata -> mm_interconnect_0:altpll_0_pll_slave_readdata
	wire   [1:0] mm_interconnect_0_altpll_0_pll_slave_address;                // mm_interconnect_0:altpll_0_pll_slave_address -> altpll_0:address
	wire         mm_interconnect_0_altpll_0_pll_slave_read;                   // mm_interconnect_0:altpll_0_pll_slave_read -> altpll_0:read
	wire         mm_interconnect_0_altpll_0_pll_slave_write;                  // mm_interconnect_0:altpll_0_pll_slave_write -> altpll_0:write
	wire  [31:0] mm_interconnect_0_altpll_0_pll_slave_writedata;              // mm_interconnect_0:altpll_0_pll_slave_writedata -> altpll_0:writedata
	wire         mm_interconnect_0_lcd_bl_s1_chipselect;                      // mm_interconnect_0:lcd_bl_s1_chipselect -> lcd_bl:chipselect
	wire  [31:0] mm_interconnect_0_lcd_bl_s1_readdata;                        // lcd_bl:readdata -> mm_interconnect_0:lcd_bl_s1_readdata
	wire   [1:0] mm_interconnect_0_lcd_bl_s1_address;                         // mm_interconnect_0:lcd_bl_s1_address -> lcd_bl:address
	wire         mm_interconnect_0_lcd_bl_s1_write;                           // mm_interconnect_0:lcd_bl_s1_write -> lcd_bl:write_n
	wire  [31:0] mm_interconnect_0_lcd_bl_s1_writedata;                       // mm_interconnect_0:lcd_bl_s1_writedata -> lcd_bl:writedata
	wire         mm_interconnect_0_lcd_rst_s1_chipselect;                     // mm_interconnect_0:lcd_rst_s1_chipselect -> lcd_rst:chipselect
	wire  [31:0] mm_interconnect_0_lcd_rst_s1_readdata;                       // lcd_rst:readdata -> mm_interconnect_0:lcd_rst_s1_readdata
	wire   [1:0] mm_interconnect_0_lcd_rst_s1_address;                        // mm_interconnect_0:lcd_rst_s1_address -> lcd_rst:address
	wire         mm_interconnect_0_lcd_rst_s1_write;                          // mm_interconnect_0:lcd_rst_s1_write -> lcd_rst:write_n
	wire  [31:0] mm_interconnect_0_lcd_rst_s1_writedata;                      // mm_interconnect_0:lcd_rst_s1_writedata -> lcd_rst:writedata
	wire         mm_interconnect_0_sdram_s1_chipselect;                       // mm_interconnect_0:sdram_s1_chipselect -> sdram:az_cs
	wire  [15:0] mm_interconnect_0_sdram_s1_readdata;                         // sdram:za_data -> mm_interconnect_0:sdram_s1_readdata
	wire         mm_interconnect_0_sdram_s1_waitrequest;                      // sdram:za_waitrequest -> mm_interconnect_0:sdram_s1_waitrequest
	wire  [22:0] mm_interconnect_0_sdram_s1_address;                          // mm_interconnect_0:sdram_s1_address -> sdram:az_addr
	wire         mm_interconnect_0_sdram_s1_read;                             // mm_interconnect_0:sdram_s1_read -> sdram:az_rd_n
	wire   [1:0] mm_interconnect_0_sdram_s1_byteenable;                       // mm_interconnect_0:sdram_s1_byteenable -> sdram:az_be_n
	wire         mm_interconnect_0_sdram_s1_readdatavalid;                    // sdram:za_valid -> mm_interconnect_0:sdram_s1_readdatavalid
	wire         mm_interconnect_0_sdram_s1_write;                            // mm_interconnect_0:sdram_s1_write -> sdram:az_wr_n
	wire  [15:0] mm_interconnect_0_sdram_s1_writedata;                        // mm_interconnect_0:sdram_s1_writedata -> sdram:az_data
	wire         mm_interconnect_0_uart_0_s1_chipselect;                      // mm_interconnect_0:uart_0_s1_chipselect -> uart_0:chipselect
	wire  [15:0] mm_interconnect_0_uart_0_s1_readdata;                        // uart_0:readdata -> mm_interconnect_0:uart_0_s1_readdata
	wire   [2:0] mm_interconnect_0_uart_0_s1_address;                         // mm_interconnect_0:uart_0_s1_address -> uart_0:address
	wire         mm_interconnect_0_uart_0_s1_read;                            // mm_interconnect_0:uart_0_s1_read -> uart_0:read_n
	wire         mm_interconnect_0_uart_0_s1_begintransfer;                   // mm_interconnect_0:uart_0_s1_begintransfer -> uart_0:begintransfer
	wire         mm_interconnect_0_uart_0_s1_write;                           // mm_interconnect_0:uart_0_s1_write -> uart_0:write_n
	wire  [15:0] mm_interconnect_0_uart_0_s1_writedata;                       // mm_interconnect_0:uart_0_s1_writedata -> uart_0:writedata
	wire         mm_interconnect_0_pio0_inc_s1_chipselect;                    // mm_interconnect_0:pio0_inc_s1_chipselect -> pio0_inc:chipselect
	wire  [31:0] mm_interconnect_0_pio0_inc_s1_readdata;                      // pio0_inc:readdata -> mm_interconnect_0:pio0_inc_s1_readdata
	wire   [1:0] mm_interconnect_0_pio0_inc_s1_address;                       // mm_interconnect_0:pio0_inc_s1_address -> pio0_inc:address
	wire         mm_interconnect_0_pio0_inc_s1_write;                         // mm_interconnect_0:pio0_inc_s1_write -> pio0_inc:write_n
	wire  [31:0] mm_interconnect_0_pio0_inc_s1_writedata;                     // mm_interconnect_0:pio0_inc_s1_writedata -> pio0_inc:writedata
	wire  [31:0] mm_interconnect_0_pio1_sw_s1_readdata;                       // pio1_sw:readdata -> mm_interconnect_0:pio1_sw_s1_readdata
	wire   [1:0] mm_interconnect_0_pio1_sw_s1_address;                        // mm_interconnect_0:pio1_sw_s1_address -> pio1_sw:address
	wire         mm_interconnect_0_pio2_led_s1_chipselect;                    // mm_interconnect_0:pio2_led_s1_chipselect -> pio2_led:chipselect
	wire  [31:0] mm_interconnect_0_pio2_led_s1_readdata;                      // pio2_led:readdata -> mm_interconnect_0:pio2_led_s1_readdata
	wire   [1:0] mm_interconnect_0_pio2_led_s1_address;                       // mm_interconnect_0:pio2_led_s1_address -> pio2_led:address
	wire         mm_interconnect_0_pio2_led_s1_write;                         // mm_interconnect_0:pio2_led_s1_write -> pio2_led:write_n
	wire  [31:0] mm_interconnect_0_pio2_led_s1_writedata;                     // mm_interconnect_0:pio2_led_s1_writedata -> pio2_led:writedata
	wire  [31:0] mm_interconnect_0_pio3_btn_s1_readdata;                      // pio3_btn:readdata -> mm_interconnect_0:pio3_btn_s1_readdata
	wire   [1:0] mm_interconnect_0_pio3_btn_s1_address;                       // mm_interconnect_0:pio3_btn_s1_address -> pio3_btn:address
	wire  [31:0] mm_interconnect_0_pio4_vpp_adc1_s1_readdata;                 // pio4_vpp_adc1:readdata -> mm_interconnect_0:pio4_vpp_adc1_s1_readdata
	wire   [1:0] mm_interconnect_0_pio4_vpp_adc1_s1_address;                  // mm_interconnect_0:pio4_vpp_adc1_s1_address -> pio4_vpp_adc1:address
	wire  [31:0] mm_interconnect_0_pio5_vpp_adc0_s1_readdata;                 // pio5_vpp_adc0:readdata -> mm_interconnect_0:pio5_vpp_adc0_s1_readdata
	wire   [1:0] mm_interconnect_0_pio5_vpp_adc0_s1_address;                  // mm_interconnect_0:pio5_vpp_adc0_s1_address -> pio5_vpp_adc0:address
	wire         mm_interconnect_0_pio6_mul_s1_chipselect;                    // mm_interconnect_0:pio6_mul_s1_chipselect -> pio6_mul:chipselect
	wire  [31:0] mm_interconnect_0_pio6_mul_s1_readdata;                      // pio6_mul:readdata -> mm_interconnect_0:pio6_mul_s1_readdata
	wire   [1:0] mm_interconnect_0_pio6_mul_s1_address;                       // mm_interconnect_0:pio6_mul_s1_address -> pio6_mul:address
	wire         mm_interconnect_0_pio6_mul_s1_write;                         // mm_interconnect_0:pio6_mul_s1_write -> pio6_mul:write_n
	wire  [31:0] mm_interconnect_0_pio6_mul_s1_writedata;                     // mm_interconnect_0:pio6_mul_s1_writedata -> pio6_mul:writedata
	wire         mm_interconnect_0_pio7_filter_work_s1_chipselect;            // mm_interconnect_0:pio7_filter_work_s1_chipselect -> pio7_filter_work:chipselect
	wire  [31:0] mm_interconnect_0_pio7_filter_work_s1_readdata;              // pio7_filter_work:readdata -> mm_interconnect_0:pio7_filter_work_s1_readdata
	wire   [1:0] mm_interconnect_0_pio7_filter_work_s1_address;               // mm_interconnect_0:pio7_filter_work_s1_address -> pio7_filter_work:address
	wire         mm_interconnect_0_pio7_filter_work_s1_write;                 // mm_interconnect_0:pio7_filter_work_s1_write -> pio7_filter_work:write_n
	wire  [31:0] mm_interconnect_0_pio7_filter_work_s1_writedata;             // mm_interconnect_0:pio7_filter_work_s1_writedata -> pio7_filter_work:writedata
	wire         mm_interconnect_0_pio8_filter_addr_s1_chipselect;            // mm_interconnect_0:pio8_filter_addr_s1_chipselect -> pio8_filter_addr:chipselect
	wire  [31:0] mm_interconnect_0_pio8_filter_addr_s1_readdata;              // pio8_filter_addr:readdata -> mm_interconnect_0:pio8_filter_addr_s1_readdata
	wire   [1:0] mm_interconnect_0_pio8_filter_addr_s1_address;               // mm_interconnect_0:pio8_filter_addr_s1_address -> pio8_filter_addr:address
	wire         mm_interconnect_0_pio8_filter_addr_s1_write;                 // mm_interconnect_0:pio8_filter_addr_s1_write -> pio8_filter_addr:write_n
	wire  [31:0] mm_interconnect_0_pio8_filter_addr_s1_writedata;             // mm_interconnect_0:pio8_filter_addr_s1_writedata -> pio8_filter_addr:writedata
	wire         mm_interconnect_0_pio9_filter_data_s1_chipselect;            // mm_interconnect_0:pio9_filter_data_s1_chipselect -> pio9_filter_data:chipselect
	wire  [31:0] mm_interconnect_0_pio9_filter_data_s1_readdata;              // pio9_filter_data:readdata -> mm_interconnect_0:pio9_filter_data_s1_readdata
	wire   [1:0] mm_interconnect_0_pio9_filter_data_s1_address;               // mm_interconnect_0:pio9_filter_data_s1_address -> pio9_filter_data:address
	wire         mm_interconnect_0_pio9_filter_data_s1_write;                 // mm_interconnect_0:pio9_filter_data_s1_write -> pio9_filter_data:write_n
	wire  [31:0] mm_interconnect_0_pio9_filter_data_s1_writedata;             // mm_interconnect_0:pio9_filter_data_s1_writedata -> pio9_filter_data:writedata
	wire         mm_interconnect_0_pio10_filter_write_s1_chipselect;          // mm_interconnect_0:pio10_filter_write_s1_chipselect -> pio10_filter_write:chipselect
	wire  [31:0] mm_interconnect_0_pio10_filter_write_s1_readdata;            // pio10_filter_write:readdata -> mm_interconnect_0:pio10_filter_write_s1_readdata
	wire   [1:0] mm_interconnect_0_pio10_filter_write_s1_address;             // mm_interconnect_0:pio10_filter_write_s1_address -> pio10_filter_write:address
	wire         mm_interconnect_0_pio10_filter_write_s1_write;               // mm_interconnect_0:pio10_filter_write_s1_write -> pio10_filter_write:write_n
	wire  [31:0] mm_interconnect_0_pio10_filter_write_s1_writedata;           // mm_interconnect_0:pio10_filter_write_s1_writedata -> pio10_filter_write:writedata
	wire         irq_mapper_receiver0_irq;                                    // Ir_HT6221_Decode_Irq_0:irq_out -> irq_mapper:receiver0_irq
	wire         irq_mapper_receiver1_irq;                                    // jtag_uart_0:av_irq -> irq_mapper:receiver1_irq
	wire         irq_mapper_receiver2_irq;                                    // uart_0:irq -> irq_mapper:receiver2_irq
	wire         irq_mapper_receiver3_irq;                                    // epcs:irq -> irq_mapper:receiver3_irq
	wire  [31:0] nios2_irq_irq;                                               // irq_mapper:sender_irq -> nios2:irq
	wire         rst_controller_reset_out_reset;                              // rst_controller:reset_out -> [altpll_0:reset, mm_interconnect_0:altpll_0_inclk_interface_reset_reset_bridge_in_reset_reset]
	wire         rst_controller_001_reset_out_reset;                          // rst_controller_001:reset_out -> [epcs:reset_n, irq_mapper:reset, jtag_uart_0:rst_n, lcd:av_reset_n, lcd_bl:reset_n, lcd_rst:reset_n, mm_interconnect_0:nios2_reset_reset_bridge_in_reset_reset, nios2:reset_n, rst_translator:in_reset, sdram:reset_n, uart_0:reset_n]
	wire         rst_controller_001_reset_out_reset_req;                      // rst_controller_001:reset_req -> [epcs:reset_req, nios2:reset_req, rst_translator:reset_req_in]
	wire         nios2_debug_reset_request_reset;                             // nios2:debug_reset_request -> rst_controller_001:reset_in1
	wire         rst_controller_002_reset_out_reset;                          // rst_controller_002:reset_out -> [mm_interconnect_0:Ir_HT6221_Decode_Irq_0_reset_reset_bridge_in_reset_reset, mm_interconnect_0:pio0_inc_reset_reset_bridge_in_reset_reset, pio0_inc:reset_n, pio10_filter_write:reset_n, pio1_sw:reset_n, pio2_led:reset_n, pio3_btn:reset_n, pio4_vpp_adc1:reset_n, pio5_vpp_adc0:reset_n, pio6_mul:reset_n, pio7_filter_work:reset_n, pio8_filter_addr:reset_n, pio9_filter_data:reset_n]

	Ir_HT6221_Decode_Irq #(
		.T_Sa_Clk (10000),
		.T_Clk50m (10),
		.N_Code   (32),
		.N_Dev    (20)
	) ir_ht6221_decode_irq_0 (
		.reset_n     (reset_reset_n),                                          //            reset.reset_n
		.clk50m      (altpll_0_c0_clk),                                        //       clock_sink.clk
		.clk100k     (ir_decoder_clk100k),                                     //      conduit_end.clk100k
		.decode_ok   (ir_decoder_decode_ok),                                   //                 .decode_ok
		.decoding    (ir_decoder_decoding),                                    //                 .decoding
		.error       (ir_decoder_error),                                       //                 .error
		.ir_Data     (ir_decoder_ir_data),                                     //                 .ir_data
		.ir_AddrH    (ir_decoder_ir_addrh),                                    //                 .ir_addrh
		.ir_AddrL    (ir_decoder_ir_addrl),                                    //                 .ir_addrl
		.ir_in       (ir_decoder_ir_in),                                       //                 .ir_in
		.ir_out      (ir_decoder_ir_out),                                      //                 .ir_out
		.irq_out     (irq_mapper_receiver0_irq),                               // interrupt_sender.irq
		.CPU_CS      (mm_interconnect_0_ir_ht6221_decode_irq_0_as_chipselect), //               as.chipselect
		.CPU_RD      (mm_interconnect_0_ir_ht6221_decode_irq_0_as_read),       //                 .read
		.CPU_WR      (mm_interconnect_0_ir_ht6221_decode_irq_0_as_write),      //                 .write
		.CPU_Addr    (mm_interconnect_0_ir_ht6221_decode_irq_0_as_address),    //                 .address
		.CPU_RD_Data (mm_interconnect_0_ir_ht6221_decode_irq_0_as_readdata),   //                 .readdata
		.CPU_WR_Data (mm_interconnect_0_ir_ht6221_decode_irq_0_as_writedata)   //                 .writedata
	);

	mysystem_altpll_0 altpll_0 (
		.clk                (clk_clk),                                        //       inclk_interface.clk
		.reset              (rst_controller_reset_out_reset),                 // inclk_interface_reset.reset
		.read               (mm_interconnect_0_altpll_0_pll_slave_read),      //             pll_slave.read
		.write              (mm_interconnect_0_altpll_0_pll_slave_write),     //                      .write
		.address            (mm_interconnect_0_altpll_0_pll_slave_address),   //                      .address
		.readdata           (mm_interconnect_0_altpll_0_pll_slave_readdata),  //                      .readdata
		.writedata          (mm_interconnect_0_altpll_0_pll_slave_writedata), //                      .writedata
		.c0                 (altpll_0_c0_clk),                                //                    c0.clk
		.c1                 (sdram_clk_clk),                                  //                    c1.clk
		.c2                 (clk20m_clk),                                     //                    c2.clk
		.scandone           (),                                               //           (terminated)
		.scandataout        (),                                               //           (terminated)
		.areset             (1'b0),                                           //           (terminated)
		.locked             (),                                               //           (terminated)
		.phasedone          (),                                               //           (terminated)
		.phasecounterselect (4'b0000),                                        //           (terminated)
		.phaseupdown        (1'b0),                                           //           (terminated)
		.phasestep          (1'b0),                                           //           (terminated)
		.scanclk            (1'b0),                                           //           (terminated)
		.scanclkena         (1'b0),                                           //           (terminated)
		.scandata           (1'b0),                                           //           (terminated)
		.configupdate       (1'b0)                                            //           (terminated)
	);

	mysystem_epcs epcs (
		.clk        (altpll_0_c0_clk),                                     //               clk.clk
		.reset_n    (~rst_controller_001_reset_out_reset),                 //             reset.reset_n
		.reset_req  (rst_controller_001_reset_out_reset_req),              //                  .reset_req
		.address    (mm_interconnect_0_epcs_epcs_control_port_address),    // epcs_control_port.address
		.chipselect (mm_interconnect_0_epcs_epcs_control_port_chipselect), //                  .chipselect
		.read_n     (~mm_interconnect_0_epcs_epcs_control_port_read),      //                  .read_n
		.readdata   (mm_interconnect_0_epcs_epcs_control_port_readdata),   //                  .readdata
		.write_n    (~mm_interconnect_0_epcs_epcs_control_port_write),     //                  .write_n
		.writedata  (mm_interconnect_0_epcs_epcs_control_port_writedata),  //                  .writedata
		.irq        (irq_mapper_receiver3_irq),                            //               irq.irq
		.dclk       (epcs_dclk),                                           //          external.export
		.sce        (epcs_sce),                                            //                  .export
		.sdo        (epcs_sdo),                                            //                  .export
		.data0      (epcs_data0)                                           //                  .export
	);

	mysystem_jtag_uart_0 jtag_uart_0 (
		.clk            (altpll_0_c0_clk),                                             //               clk.clk
		.rst_n          (~rst_controller_001_reset_out_reset),                         //             reset.reset_n
		.av_chipselect  (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_chipselect),  // avalon_jtag_slave.chipselect
		.av_address     (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_address),     //                  .address
		.av_read_n      (~mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_read),       //                  .read_n
		.av_readdata    (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_readdata),    //                  .readdata
		.av_write_n     (~mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_write),      //                  .write_n
		.av_writedata   (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_writedata),   //                  .writedata
		.av_waitrequest (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_waitrequest), //                  .waitrequest
		.av_irq         (irq_mapper_receiver1_irq)                                     //               irq.irq
	);

	LCD_Control lcd (
		.clk             (altpll_0_c0_clk),                      //       clock.clk
		.av_writedata    (mm_interconnect_0_lcd_av_writedata),   //          av.writedata
		.av_readdata     (mm_interconnect_0_lcd_av_readdata),    //            .readdata
		.av_addr         (mm_interconnect_0_lcd_av_address),     //            .address
		.av_chipselect_n (~mm_interconnect_0_lcd_av_chipselect), //            .chipselect_n
		.av_write_n      (~mm_interconnect_0_lcd_av_write),      //            .write_n
		.av_read_n       (~mm_interconnect_0_lcd_av_read),       //            .read_n
		.lcd_wr_n        (lcd_wr_n),                             // conduit_end.export
		.lcd_rd_n        (lcd_rd_n),                             //            .export
		.lcd_data        (lcd_data),                             //            .export
		.lcd_rs          (lcd_rs),                               //            .export
		.lcd_cs_n        (lcd_cs_n),                             //            .export
		.av_reset_n      (~rst_controller_001_reset_out_reset)   //  reset_sink.reset_n
	);

	mysystem_lcd_bl lcd_bl (
		.clk        (altpll_0_c0_clk),                        //                 clk.clk
		.reset_n    (~rst_controller_001_reset_out_reset),    //               reset.reset_n
		.address    (mm_interconnect_0_lcd_bl_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_lcd_bl_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_lcd_bl_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_lcd_bl_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_lcd_bl_s1_readdata),   //                    .readdata
		.out_port   (lcd_bl_export)                           // external_connection.export
	);

	mysystem_lcd_bl lcd_rst (
		.clk        (altpll_0_c0_clk),                         //                 clk.clk
		.reset_n    (~rst_controller_001_reset_out_reset),     //               reset.reset_n
		.address    (mm_interconnect_0_lcd_rst_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_lcd_rst_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_lcd_rst_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_lcd_rst_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_lcd_rst_s1_readdata),   //                    .readdata
		.out_port   (lcd_rst_export)                           // external_connection.export
	);

	mysystem_nios2 nios2 (
		.clk                                 (altpll_0_c0_clk),                                     //                       clk.clk
		.reset_n                             (~rst_controller_001_reset_out_reset),                 //                     reset.reset_n
		.reset_req                           (rst_controller_001_reset_out_reset_req),              //                          .reset_req
		.d_address                           (nios2_data_master_address),                           //               data_master.address
		.d_byteenable                        (nios2_data_master_byteenable),                        //                          .byteenable
		.d_read                              (nios2_data_master_read),                              //                          .read
		.d_readdata                          (nios2_data_master_readdata),                          //                          .readdata
		.d_waitrequest                       (nios2_data_master_waitrequest),                       //                          .waitrequest
		.d_write                             (nios2_data_master_write),                             //                          .write
		.d_writedata                         (nios2_data_master_writedata),                         //                          .writedata
		.d_readdatavalid                     (nios2_data_master_readdatavalid),                     //                          .readdatavalid
		.debug_mem_slave_debugaccess_to_roms (nios2_data_master_debugaccess),                       //                          .debugaccess
		.i_address                           (nios2_instruction_master_address),                    //        instruction_master.address
		.i_read                              (nios2_instruction_master_read),                       //                          .read
		.i_readdata                          (nios2_instruction_master_readdata),                   //                          .readdata
		.i_waitrequest                       (nios2_instruction_master_waitrequest),                //                          .waitrequest
		.i_readdatavalid                     (nios2_instruction_master_readdatavalid),              //                          .readdatavalid
		.irq                                 (nios2_irq_irq),                                       //                       irq.irq
		.debug_reset_request                 (nios2_debug_reset_request_reset),                     //       debug_reset_request.reset
		.debug_mem_slave_address             (mm_interconnect_0_nios2_debug_mem_slave_address),     //           debug_mem_slave.address
		.debug_mem_slave_byteenable          (mm_interconnect_0_nios2_debug_mem_slave_byteenable),  //                          .byteenable
		.debug_mem_slave_debugaccess         (mm_interconnect_0_nios2_debug_mem_slave_debugaccess), //                          .debugaccess
		.debug_mem_slave_read                (mm_interconnect_0_nios2_debug_mem_slave_read),        //                          .read
		.debug_mem_slave_readdata            (mm_interconnect_0_nios2_debug_mem_slave_readdata),    //                          .readdata
		.debug_mem_slave_waitrequest         (mm_interconnect_0_nios2_debug_mem_slave_waitrequest), //                          .waitrequest
		.debug_mem_slave_write               (mm_interconnect_0_nios2_debug_mem_slave_write),       //                          .write
		.debug_mem_slave_writedata           (mm_interconnect_0_nios2_debug_mem_slave_writedata),   //                          .writedata
		.dummy_ci_port                       ()                                                     // custom_instruction_master.readra
	);

	mysystem_pio0_inc pio0_inc (
		.clk        (altpll_0_c0_clk),                          //                 clk.clk
		.reset_n    (~rst_controller_002_reset_out_reset),      //               reset.reset_n
		.address    (mm_interconnect_0_pio0_inc_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_pio0_inc_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_pio0_inc_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_pio0_inc_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_pio0_inc_s1_readdata),   //                    .readdata
		.out_port   (pio0_inc_export)                           // external_connection.export
	);

	mysystem_pio10_filter_write pio10_filter_write (
		.clk        (altpll_0_c0_clk),                                    //                 clk.clk
		.reset_n    (~rst_controller_002_reset_out_reset),                //               reset.reset_n
		.address    (mm_interconnect_0_pio10_filter_write_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_pio10_filter_write_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_pio10_filter_write_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_pio10_filter_write_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_pio10_filter_write_s1_readdata),   //                    .readdata
		.out_port   (filter_write_export)                                 // external_connection.export
	);

	mysystem_pio1_sw pio1_sw (
		.clk      (altpll_0_c0_clk),                       //                 clk.clk
		.reset_n  (~rst_controller_002_reset_out_reset),   //               reset.reset_n
		.address  (mm_interconnect_0_pio1_sw_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_pio1_sw_s1_readdata), //                    .readdata
		.in_port  (meisw_export)                           // external_connection.export
	);

	mysystem_pio2_led pio2_led (
		.clk        (altpll_0_c0_clk),                          //                 clk.clk
		.reset_n    (~rst_controller_002_reset_out_reset),      //               reset.reset_n
		.address    (mm_interconnect_0_pio2_led_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_pio2_led_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_pio2_led_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_pio2_led_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_pio2_led_s1_readdata),   //                    .readdata
		.out_port   (meiled_export)                             // external_connection.export
	);

	mysystem_pio3_btn pio3_btn (
		.clk      (altpll_0_c0_clk),                        //                 clk.clk
		.reset_n  (~rst_controller_002_reset_out_reset),    //               reset.reset_n
		.address  (mm_interconnect_0_pio3_btn_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_pio3_btn_s1_readdata), //                    .readdata
		.in_port  (btn_export)                              // external_connection.export
	);

	mysystem_pio1_sw pio4_vpp_adc1 (
		.clk      (altpll_0_c0_clk),                             //                 clk.clk
		.reset_n  (~rst_controller_002_reset_out_reset),         //               reset.reset_n
		.address  (mm_interconnect_0_pio4_vpp_adc1_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_pio4_vpp_adc1_s1_readdata), //                    .readdata
		.in_port  (vpp_adc1_export)                              // external_connection.export
	);

	mysystem_pio1_sw pio5_vpp_adc0 (
		.clk      (altpll_0_c0_clk),                             //                 clk.clk
		.reset_n  (~rst_controller_002_reset_out_reset),         //               reset.reset_n
		.address  (mm_interconnect_0_pio5_vpp_adc0_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_pio5_vpp_adc0_s1_readdata), //                    .readdata
		.in_port  (vpp_adc0_export)                              // external_connection.export
	);

	mysystem_pio6_mul pio6_mul (
		.clk        (altpll_0_c0_clk),                          //                 clk.clk
		.reset_n    (~rst_controller_002_reset_out_reset),      //               reset.reset_n
		.address    (mm_interconnect_0_pio6_mul_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_pio6_mul_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_pio6_mul_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_pio6_mul_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_pio6_mul_s1_readdata),   //                    .readdata
		.out_port   (mul_export)                                // external_connection.export
	);

	mysystem_pio10_filter_write pio7_filter_work (
		.clk        (altpll_0_c0_clk),                                  //                 clk.clk
		.reset_n    (~rst_controller_002_reset_out_reset),              //               reset.reset_n
		.address    (mm_interconnect_0_pio7_filter_work_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_pio7_filter_work_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_pio7_filter_work_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_pio7_filter_work_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_pio7_filter_work_s1_readdata),   //                    .readdata
		.out_port   (filter_work_export)                                // external_connection.export
	);

	mysystem_pio8_filter_addr pio8_filter_addr (
		.clk        (altpll_0_c0_clk),                                  //                 clk.clk
		.reset_n    (~rst_controller_002_reset_out_reset),              //               reset.reset_n
		.address    (mm_interconnect_0_pio8_filter_addr_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_pio8_filter_addr_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_pio8_filter_addr_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_pio8_filter_addr_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_pio8_filter_addr_s1_readdata),   //                    .readdata
		.out_port   (filter_addr_export)                                // external_connection.export
	);

	mysystem_pio9_filter_data pio9_filter_data (
		.clk        (altpll_0_c0_clk),                                  //                 clk.clk
		.reset_n    (~rst_controller_002_reset_out_reset),              //               reset.reset_n
		.address    (mm_interconnect_0_pio9_filter_data_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_pio9_filter_data_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_pio9_filter_data_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_pio9_filter_data_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_pio9_filter_data_s1_readdata),   //                    .readdata
		.out_port   (filter_data_export)                                // external_connection.export
	);

	mysystem_sdram sdram (
		.clk            (altpll_0_c0_clk),                          //   clk.clk
		.reset_n        (~rst_controller_001_reset_out_reset),      // reset.reset_n
		.az_addr        (mm_interconnect_0_sdram_s1_address),       //    s1.address
		.az_be_n        (~mm_interconnect_0_sdram_s1_byteenable),   //      .byteenable_n
		.az_cs          (mm_interconnect_0_sdram_s1_chipselect),    //      .chipselect
		.az_data        (mm_interconnect_0_sdram_s1_writedata),     //      .writedata
		.az_rd_n        (~mm_interconnect_0_sdram_s1_read),         //      .read_n
		.az_wr_n        (~mm_interconnect_0_sdram_s1_write),        //      .write_n
		.za_data        (mm_interconnect_0_sdram_s1_readdata),      //      .readdata
		.za_valid       (mm_interconnect_0_sdram_s1_readdatavalid), //      .readdatavalid
		.za_waitrequest (mm_interconnect_0_sdram_s1_waitrequest),   //      .waitrequest
		.zs_addr        (sdram_addr),                               //  wire.export
		.zs_ba          (sdram_ba),                                 //      .export
		.zs_cas_n       (sdram_cas_n),                              //      .export
		.zs_cke         (sdram_cke),                                //      .export
		.zs_cs_n        (sdram_cs_n),                               //      .export
		.zs_dq          (sdram_dq),                                 //      .export
		.zs_dqm         (sdram_dqm),                                //      .export
		.zs_ras_n       (sdram_ras_n),                              //      .export
		.zs_we_n        (sdram_we_n)                                //      .export
	);

	mysystem_uart_0 uart_0 (
		.clk           (altpll_0_c0_clk),                           //                 clk.clk
		.reset_n       (~rst_controller_001_reset_out_reset),       //               reset.reset_n
		.address       (mm_interconnect_0_uart_0_s1_address),       //                  s1.address
		.begintransfer (mm_interconnect_0_uart_0_s1_begintransfer), //                    .begintransfer
		.chipselect    (mm_interconnect_0_uart_0_s1_chipselect),    //                    .chipselect
		.read_n        (~mm_interconnect_0_uart_0_s1_read),         //                    .read_n
		.write_n       (~mm_interconnect_0_uart_0_s1_write),        //                    .write_n
		.writedata     (mm_interconnect_0_uart_0_s1_writedata),     //                    .writedata
		.readdata      (mm_interconnect_0_uart_0_s1_readdata),      //                    .readdata
		.rxd           (uart_0_rxd),                                // external_connection.export
		.txd           (uart_0_txd),                                //                    .export
		.irq           (irq_mapper_receiver2_irq)                   //                 irq.irq
	);

	mysystem_mm_interconnect_0 mm_interconnect_0 (
		.altpll_0_c0_clk                                            (altpll_0_c0_clk),                                             //                                          altpll_0_c0.clk
		.clk_0_clk_clk                                              (clk_clk),                                                     //                                            clk_0_clk.clk
		.altpll_0_inclk_interface_reset_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),                              // altpll_0_inclk_interface_reset_reset_bridge_in_reset.reset
		.Ir_HT6221_Decode_Irq_0_reset_reset_bridge_in_reset_reset   (rst_controller_002_reset_out_reset),                          //   Ir_HT6221_Decode_Irq_0_reset_reset_bridge_in_reset.reset
		.nios2_reset_reset_bridge_in_reset_reset                    (rst_controller_001_reset_out_reset),                          //                    nios2_reset_reset_bridge_in_reset.reset
		.pio0_inc_reset_reset_bridge_in_reset_reset                 (rst_controller_002_reset_out_reset),                          //                 pio0_inc_reset_reset_bridge_in_reset.reset
		.nios2_data_master_address                                  (nios2_data_master_address),                                   //                                    nios2_data_master.address
		.nios2_data_master_waitrequest                              (nios2_data_master_waitrequest),                               //                                                     .waitrequest
		.nios2_data_master_byteenable                               (nios2_data_master_byteenable),                                //                                                     .byteenable
		.nios2_data_master_read                                     (nios2_data_master_read),                                      //                                                     .read
		.nios2_data_master_readdata                                 (nios2_data_master_readdata),                                  //                                                     .readdata
		.nios2_data_master_readdatavalid                            (nios2_data_master_readdatavalid),                             //                                                     .readdatavalid
		.nios2_data_master_write                                    (nios2_data_master_write),                                     //                                                     .write
		.nios2_data_master_writedata                                (nios2_data_master_writedata),                                 //                                                     .writedata
		.nios2_data_master_debugaccess                              (nios2_data_master_debugaccess),                               //                                                     .debugaccess
		.nios2_instruction_master_address                           (nios2_instruction_master_address),                            //                             nios2_instruction_master.address
		.nios2_instruction_master_waitrequest                       (nios2_instruction_master_waitrequest),                        //                                                     .waitrequest
		.nios2_instruction_master_read                              (nios2_instruction_master_read),                               //                                                     .read
		.nios2_instruction_master_readdata                          (nios2_instruction_master_readdata),                           //                                                     .readdata
		.nios2_instruction_master_readdatavalid                     (nios2_instruction_master_readdatavalid),                      //                                                     .readdatavalid
		.altpll_0_pll_slave_address                                 (mm_interconnect_0_altpll_0_pll_slave_address),                //                                   altpll_0_pll_slave.address
		.altpll_0_pll_slave_write                                   (mm_interconnect_0_altpll_0_pll_slave_write),                  //                                                     .write
		.altpll_0_pll_slave_read                                    (mm_interconnect_0_altpll_0_pll_slave_read),                   //                                                     .read
		.altpll_0_pll_slave_readdata                                (mm_interconnect_0_altpll_0_pll_slave_readdata),               //                                                     .readdata
		.altpll_0_pll_slave_writedata                               (mm_interconnect_0_altpll_0_pll_slave_writedata),              //                                                     .writedata
		.epcs_epcs_control_port_address                             (mm_interconnect_0_epcs_epcs_control_port_address),            //                               epcs_epcs_control_port.address
		.epcs_epcs_control_port_write                               (mm_interconnect_0_epcs_epcs_control_port_write),              //                                                     .write
		.epcs_epcs_control_port_read                                (mm_interconnect_0_epcs_epcs_control_port_read),               //                                                     .read
		.epcs_epcs_control_port_readdata                            (mm_interconnect_0_epcs_epcs_control_port_readdata),           //                                                     .readdata
		.epcs_epcs_control_port_writedata                           (mm_interconnect_0_epcs_epcs_control_port_writedata),          //                                                     .writedata
		.epcs_epcs_control_port_chipselect                          (mm_interconnect_0_epcs_epcs_control_port_chipselect),         //                                                     .chipselect
		.Ir_HT6221_Decode_Irq_0_as_address                          (mm_interconnect_0_ir_ht6221_decode_irq_0_as_address),         //                            Ir_HT6221_Decode_Irq_0_as.address
		.Ir_HT6221_Decode_Irq_0_as_write                            (mm_interconnect_0_ir_ht6221_decode_irq_0_as_write),           //                                                     .write
		.Ir_HT6221_Decode_Irq_0_as_read                             (mm_interconnect_0_ir_ht6221_decode_irq_0_as_read),            //                                                     .read
		.Ir_HT6221_Decode_Irq_0_as_readdata                         (mm_interconnect_0_ir_ht6221_decode_irq_0_as_readdata),        //                                                     .readdata
		.Ir_HT6221_Decode_Irq_0_as_writedata                        (mm_interconnect_0_ir_ht6221_decode_irq_0_as_writedata),       //                                                     .writedata
		.Ir_HT6221_Decode_Irq_0_as_chipselect                       (mm_interconnect_0_ir_ht6221_decode_irq_0_as_chipselect),      //                                                     .chipselect
		.jtag_uart_0_avalon_jtag_slave_address                      (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_address),     //                        jtag_uart_0_avalon_jtag_slave.address
		.jtag_uart_0_avalon_jtag_slave_write                        (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_write),       //                                                     .write
		.jtag_uart_0_avalon_jtag_slave_read                         (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_read),        //                                                     .read
		.jtag_uart_0_avalon_jtag_slave_readdata                     (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_readdata),    //                                                     .readdata
		.jtag_uart_0_avalon_jtag_slave_writedata                    (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_writedata),   //                                                     .writedata
		.jtag_uart_0_avalon_jtag_slave_waitrequest                  (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_waitrequest), //                                                     .waitrequest
		.jtag_uart_0_avalon_jtag_slave_chipselect                   (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_chipselect),  //                                                     .chipselect
		.lcd_av_address                                             (mm_interconnect_0_lcd_av_address),                            //                                               lcd_av.address
		.lcd_av_write                                               (mm_interconnect_0_lcd_av_write),                              //                                                     .write
		.lcd_av_read                                                (mm_interconnect_0_lcd_av_read),                               //                                                     .read
		.lcd_av_readdata                                            (mm_interconnect_0_lcd_av_readdata),                           //                                                     .readdata
		.lcd_av_writedata                                           (mm_interconnect_0_lcd_av_writedata),                          //                                                     .writedata
		.lcd_av_chipselect                                          (mm_interconnect_0_lcd_av_chipselect),                         //                                                     .chipselect
		.lcd_bl_s1_address                                          (mm_interconnect_0_lcd_bl_s1_address),                         //                                            lcd_bl_s1.address
		.lcd_bl_s1_write                                            (mm_interconnect_0_lcd_bl_s1_write),                           //                                                     .write
		.lcd_bl_s1_readdata                                         (mm_interconnect_0_lcd_bl_s1_readdata),                        //                                                     .readdata
		.lcd_bl_s1_writedata                                        (mm_interconnect_0_lcd_bl_s1_writedata),                       //                                                     .writedata
		.lcd_bl_s1_chipselect                                       (mm_interconnect_0_lcd_bl_s1_chipselect),                      //                                                     .chipselect
		.lcd_rst_s1_address                                         (mm_interconnect_0_lcd_rst_s1_address),                        //                                           lcd_rst_s1.address
		.lcd_rst_s1_write                                           (mm_interconnect_0_lcd_rst_s1_write),                          //                                                     .write
		.lcd_rst_s1_readdata                                        (mm_interconnect_0_lcd_rst_s1_readdata),                       //                                                     .readdata
		.lcd_rst_s1_writedata                                       (mm_interconnect_0_lcd_rst_s1_writedata),                      //                                                     .writedata
		.lcd_rst_s1_chipselect                                      (mm_interconnect_0_lcd_rst_s1_chipselect),                     //                                                     .chipselect
		.nios2_debug_mem_slave_address                              (mm_interconnect_0_nios2_debug_mem_slave_address),             //                                nios2_debug_mem_slave.address
		.nios2_debug_mem_slave_write                                (mm_interconnect_0_nios2_debug_mem_slave_write),               //                                                     .write
		.nios2_debug_mem_slave_read                                 (mm_interconnect_0_nios2_debug_mem_slave_read),                //                                                     .read
		.nios2_debug_mem_slave_readdata                             (mm_interconnect_0_nios2_debug_mem_slave_readdata),            //                                                     .readdata
		.nios2_debug_mem_slave_writedata                            (mm_interconnect_0_nios2_debug_mem_slave_writedata),           //                                                     .writedata
		.nios2_debug_mem_slave_byteenable                           (mm_interconnect_0_nios2_debug_mem_slave_byteenable),          //                                                     .byteenable
		.nios2_debug_mem_slave_waitrequest                          (mm_interconnect_0_nios2_debug_mem_slave_waitrequest),         //                                                     .waitrequest
		.nios2_debug_mem_slave_debugaccess                          (mm_interconnect_0_nios2_debug_mem_slave_debugaccess),         //                                                     .debugaccess
		.pio0_inc_s1_address                                        (mm_interconnect_0_pio0_inc_s1_address),                       //                                          pio0_inc_s1.address
		.pio0_inc_s1_write                                          (mm_interconnect_0_pio0_inc_s1_write),                         //                                                     .write
		.pio0_inc_s1_readdata                                       (mm_interconnect_0_pio0_inc_s1_readdata),                      //                                                     .readdata
		.pio0_inc_s1_writedata                                      (mm_interconnect_0_pio0_inc_s1_writedata),                     //                                                     .writedata
		.pio0_inc_s1_chipselect                                     (mm_interconnect_0_pio0_inc_s1_chipselect),                    //                                                     .chipselect
		.pio10_filter_write_s1_address                              (mm_interconnect_0_pio10_filter_write_s1_address),             //                                pio10_filter_write_s1.address
		.pio10_filter_write_s1_write                                (mm_interconnect_0_pio10_filter_write_s1_write),               //                                                     .write
		.pio10_filter_write_s1_readdata                             (mm_interconnect_0_pio10_filter_write_s1_readdata),            //                                                     .readdata
		.pio10_filter_write_s1_writedata                            (mm_interconnect_0_pio10_filter_write_s1_writedata),           //                                                     .writedata
		.pio10_filter_write_s1_chipselect                           (mm_interconnect_0_pio10_filter_write_s1_chipselect),          //                                                     .chipselect
		.pio1_sw_s1_address                                         (mm_interconnect_0_pio1_sw_s1_address),                        //                                           pio1_sw_s1.address
		.pio1_sw_s1_readdata                                        (mm_interconnect_0_pio1_sw_s1_readdata),                       //                                                     .readdata
		.pio2_led_s1_address                                        (mm_interconnect_0_pio2_led_s1_address),                       //                                          pio2_led_s1.address
		.pio2_led_s1_write                                          (mm_interconnect_0_pio2_led_s1_write),                         //                                                     .write
		.pio2_led_s1_readdata                                       (mm_interconnect_0_pio2_led_s1_readdata),                      //                                                     .readdata
		.pio2_led_s1_writedata                                      (mm_interconnect_0_pio2_led_s1_writedata),                     //                                                     .writedata
		.pio2_led_s1_chipselect                                     (mm_interconnect_0_pio2_led_s1_chipselect),                    //                                                     .chipselect
		.pio3_btn_s1_address                                        (mm_interconnect_0_pio3_btn_s1_address),                       //                                          pio3_btn_s1.address
		.pio3_btn_s1_readdata                                       (mm_interconnect_0_pio3_btn_s1_readdata),                      //                                                     .readdata
		.pio4_vpp_adc1_s1_address                                   (mm_interconnect_0_pio4_vpp_adc1_s1_address),                  //                                     pio4_vpp_adc1_s1.address
		.pio4_vpp_adc1_s1_readdata                                  (mm_interconnect_0_pio4_vpp_adc1_s1_readdata),                 //                                                     .readdata
		.pio5_vpp_adc0_s1_address                                   (mm_interconnect_0_pio5_vpp_adc0_s1_address),                  //                                     pio5_vpp_adc0_s1.address
		.pio5_vpp_adc0_s1_readdata                                  (mm_interconnect_0_pio5_vpp_adc0_s1_readdata),                 //                                                     .readdata
		.pio6_mul_s1_address                                        (mm_interconnect_0_pio6_mul_s1_address),                       //                                          pio6_mul_s1.address
		.pio6_mul_s1_write                                          (mm_interconnect_0_pio6_mul_s1_write),                         //                                                     .write
		.pio6_mul_s1_readdata                                       (mm_interconnect_0_pio6_mul_s1_readdata),                      //                                                     .readdata
		.pio6_mul_s1_writedata                                      (mm_interconnect_0_pio6_mul_s1_writedata),                     //                                                     .writedata
		.pio6_mul_s1_chipselect                                     (mm_interconnect_0_pio6_mul_s1_chipselect),                    //                                                     .chipselect
		.pio7_filter_work_s1_address                                (mm_interconnect_0_pio7_filter_work_s1_address),               //                                  pio7_filter_work_s1.address
		.pio7_filter_work_s1_write                                  (mm_interconnect_0_pio7_filter_work_s1_write),                 //                                                     .write
		.pio7_filter_work_s1_readdata                               (mm_interconnect_0_pio7_filter_work_s1_readdata),              //                                                     .readdata
		.pio7_filter_work_s1_writedata                              (mm_interconnect_0_pio7_filter_work_s1_writedata),             //                                                     .writedata
		.pio7_filter_work_s1_chipselect                             (mm_interconnect_0_pio7_filter_work_s1_chipselect),            //                                                     .chipselect
		.pio8_filter_addr_s1_address                                (mm_interconnect_0_pio8_filter_addr_s1_address),               //                                  pio8_filter_addr_s1.address
		.pio8_filter_addr_s1_write                                  (mm_interconnect_0_pio8_filter_addr_s1_write),                 //                                                     .write
		.pio8_filter_addr_s1_readdata                               (mm_interconnect_0_pio8_filter_addr_s1_readdata),              //                                                     .readdata
		.pio8_filter_addr_s1_writedata                              (mm_interconnect_0_pio8_filter_addr_s1_writedata),             //                                                     .writedata
		.pio8_filter_addr_s1_chipselect                             (mm_interconnect_0_pio8_filter_addr_s1_chipselect),            //                                                     .chipselect
		.pio9_filter_data_s1_address                                (mm_interconnect_0_pio9_filter_data_s1_address),               //                                  pio9_filter_data_s1.address
		.pio9_filter_data_s1_write                                  (mm_interconnect_0_pio9_filter_data_s1_write),                 //                                                     .write
		.pio9_filter_data_s1_readdata                               (mm_interconnect_0_pio9_filter_data_s1_readdata),              //                                                     .readdata
		.pio9_filter_data_s1_writedata                              (mm_interconnect_0_pio9_filter_data_s1_writedata),             //                                                     .writedata
		.pio9_filter_data_s1_chipselect                             (mm_interconnect_0_pio9_filter_data_s1_chipselect),            //                                                     .chipselect
		.sdram_s1_address                                           (mm_interconnect_0_sdram_s1_address),                          //                                             sdram_s1.address
		.sdram_s1_write                                             (mm_interconnect_0_sdram_s1_write),                            //                                                     .write
		.sdram_s1_read                                              (mm_interconnect_0_sdram_s1_read),                             //                                                     .read
		.sdram_s1_readdata                                          (mm_interconnect_0_sdram_s1_readdata),                         //                                                     .readdata
		.sdram_s1_writedata                                         (mm_interconnect_0_sdram_s1_writedata),                        //                                                     .writedata
		.sdram_s1_byteenable                                        (mm_interconnect_0_sdram_s1_byteenable),                       //                                                     .byteenable
		.sdram_s1_readdatavalid                                     (mm_interconnect_0_sdram_s1_readdatavalid),                    //                                                     .readdatavalid
		.sdram_s1_waitrequest                                       (mm_interconnect_0_sdram_s1_waitrequest),                      //                                                     .waitrequest
		.sdram_s1_chipselect                                        (mm_interconnect_0_sdram_s1_chipselect),                       //                                                     .chipselect
		.uart_0_s1_address                                          (mm_interconnect_0_uart_0_s1_address),                         //                                            uart_0_s1.address
		.uart_0_s1_write                                            (mm_interconnect_0_uart_0_s1_write),                           //                                                     .write
		.uart_0_s1_read                                             (mm_interconnect_0_uart_0_s1_read),                            //                                                     .read
		.uart_0_s1_readdata                                         (mm_interconnect_0_uart_0_s1_readdata),                        //                                                     .readdata
		.uart_0_s1_writedata                                        (mm_interconnect_0_uart_0_s1_writedata),                       //                                                     .writedata
		.uart_0_s1_begintransfer                                    (mm_interconnect_0_uart_0_s1_begintransfer),                   //                                                     .begintransfer
		.uart_0_s1_chipselect                                       (mm_interconnect_0_uart_0_s1_chipselect)                       //                                                     .chipselect
	);

	mysystem_irq_mapper irq_mapper (
		.clk           (altpll_0_c0_clk),                    //       clk.clk
		.reset         (rst_controller_001_reset_out_reset), // clk_reset.reset
		.receiver0_irq (irq_mapper_receiver0_irq),           // receiver0.irq
		.receiver1_irq (irq_mapper_receiver1_irq),           // receiver1.irq
		.receiver2_irq (irq_mapper_receiver2_irq),           // receiver2.irq
		.receiver3_irq (irq_mapper_receiver3_irq),           // receiver3.irq
		.sender_irq    (nios2_irq_irq)                       //    sender.irq
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~reset_reset_n),                 // reset_in0.reset
		.clk            (clk_clk),                        //       clk.clk
		.reset_out      (rst_controller_reset_out_reset), // reset_out.reset
		.reset_req      (),                               // (terminated)
		.reset_req_in0  (1'b0),                           // (terminated)
		.reset_in1      (1'b0),                           // (terminated)
		.reset_req_in1  (1'b0),                           // (terminated)
		.reset_in2      (1'b0),                           // (terminated)
		.reset_req_in2  (1'b0),                           // (terminated)
		.reset_in3      (1'b0),                           // (terminated)
		.reset_req_in3  (1'b0),                           // (terminated)
		.reset_in4      (1'b0),                           // (terminated)
		.reset_req_in4  (1'b0),                           // (terminated)
		.reset_in5      (1'b0),                           // (terminated)
		.reset_req_in5  (1'b0),                           // (terminated)
		.reset_in6      (1'b0),                           // (terminated)
		.reset_req_in6  (1'b0),                           // (terminated)
		.reset_in7      (1'b0),                           // (terminated)
		.reset_req_in7  (1'b0),                           // (terminated)
		.reset_in8      (1'b0),                           // (terminated)
		.reset_req_in8  (1'b0),                           // (terminated)
		.reset_in9      (1'b0),                           // (terminated)
		.reset_req_in9  (1'b0),                           // (terminated)
		.reset_in10     (1'b0),                           // (terminated)
		.reset_req_in10 (1'b0),                           // (terminated)
		.reset_in11     (1'b0),                           // (terminated)
		.reset_req_in11 (1'b0),                           // (terminated)
		.reset_in12     (1'b0),                           // (terminated)
		.reset_req_in12 (1'b0),                           // (terminated)
		.reset_in13     (1'b0),                           // (terminated)
		.reset_req_in13 (1'b0),                           // (terminated)
		.reset_in14     (1'b0),                           // (terminated)
		.reset_req_in14 (1'b0),                           // (terminated)
		.reset_in15     (1'b0),                           // (terminated)
		.reset_req_in15 (1'b0)                            // (terminated)
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (2),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_001 (
		.reset_in0      (~reset_reset_n),                         // reset_in0.reset
		.reset_in1      (nios2_debug_reset_request_reset),        // reset_in1.reset
		.clk            (altpll_0_c0_clk),                        //       clk.clk
		.reset_out      (rst_controller_001_reset_out_reset),     // reset_out.reset
		.reset_req      (rst_controller_001_reset_out_reset_req), //          .reset_req
		.reset_req_in0  (1'b0),                                   // (terminated)
		.reset_req_in1  (1'b0),                                   // (terminated)
		.reset_in2      (1'b0),                                   // (terminated)
		.reset_req_in2  (1'b0),                                   // (terminated)
		.reset_in3      (1'b0),                                   // (terminated)
		.reset_req_in3  (1'b0),                                   // (terminated)
		.reset_in4      (1'b0),                                   // (terminated)
		.reset_req_in4  (1'b0),                                   // (terminated)
		.reset_in5      (1'b0),                                   // (terminated)
		.reset_req_in5  (1'b0),                                   // (terminated)
		.reset_in6      (1'b0),                                   // (terminated)
		.reset_req_in6  (1'b0),                                   // (terminated)
		.reset_in7      (1'b0),                                   // (terminated)
		.reset_req_in7  (1'b0),                                   // (terminated)
		.reset_in8      (1'b0),                                   // (terminated)
		.reset_req_in8  (1'b0),                                   // (terminated)
		.reset_in9      (1'b0),                                   // (terminated)
		.reset_req_in9  (1'b0),                                   // (terminated)
		.reset_in10     (1'b0),                                   // (terminated)
		.reset_req_in10 (1'b0),                                   // (terminated)
		.reset_in11     (1'b0),                                   // (terminated)
		.reset_req_in11 (1'b0),                                   // (terminated)
		.reset_in12     (1'b0),                                   // (terminated)
		.reset_req_in12 (1'b0),                                   // (terminated)
		.reset_in13     (1'b0),                                   // (terminated)
		.reset_req_in13 (1'b0),                                   // (terminated)
		.reset_in14     (1'b0),                                   // (terminated)
		.reset_req_in14 (1'b0),                                   // (terminated)
		.reset_in15     (1'b0),                                   // (terminated)
		.reset_req_in15 (1'b0)                                    // (terminated)
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_002 (
		.reset_in0      (~reset_reset_n),                     // reset_in0.reset
		.clk            (altpll_0_c0_clk),                    //       clk.clk
		.reset_out      (rst_controller_002_reset_out_reset), // reset_out.reset
		.reset_req      (),                                   // (terminated)
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_in1      (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

endmodule
