# TCL File Generated by Component Editor 13.0
# Fri Aug 11 17:29:55 CST 2017
# DO NOT MODIFY


# 
# lcd_control "lcd_control" v1.0
# xiaomeige 2017.08.11.17:29:55
# 
# 

# 
# request TCL package from ACDS 13.0
# 
package require -exact qsys 13.0


# 
# module lcd_control
# 
set_module_property DESCRIPTION ""
set_module_property NAME lcd_control
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP corecourse
set_module_property AUTHOR xiaomeige
set_module_property DISPLAY_NAME lcd_control
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL LCD_Control
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file LCD_Control.v VERILOG PATH LCD_Control.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point av
# 
add_interface av avalon end
set_interface_property av addressUnits WORDS
set_interface_property av associatedClock clock
set_interface_property av associatedReset reset_sink
set_interface_property av bitsPerSymbol 8
set_interface_property av burstOnBurstBoundariesOnly false
set_interface_property av burstcountUnits WORDS
set_interface_property av explicitAddressSpan 0
set_interface_property av holdTime 15
set_interface_property av linewrapBursts false
set_interface_property av maximumPendingReadTransactions 0
set_interface_property av readLatency 0
set_interface_property av readWaitStates 350
set_interface_property av readWaitTime 350
set_interface_property av setupTime 0
set_interface_property av timingUnits Nanoseconds
set_interface_property av writeWaitStates 15
set_interface_property av writeWaitTime 15
set_interface_property av ENABLED true
set_interface_property av EXPORT_OF ""
set_interface_property av PORT_NAME_MAP ""
set_interface_property av SVD_ADDRESS_GROUP ""

add_interface_port av av_writedata writedata Input 16
add_interface_port av av_readdata readdata Output 16
add_interface_port av av_addr address Input 1
add_interface_port av av_chipselect_n chipselect_n Input 1
add_interface_port av av_write_n write_n Input 1
add_interface_port av av_read_n read_n Input 1
set_interface_assignment av embeddedsw.configuration.isFlash 0
set_interface_assignment av embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment av embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment av embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset reset_sink
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end lcd_wr_n export Output 1
add_interface_port conduit_end lcd_rd_n export Output 1
add_interface_port conduit_end lcd_data export Bidir 16
add_interface_port conduit_end lcd_rs export Output 1
add_interface_port conduit_end lcd_cs_n export Output 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink av_reset_n reset_n Input 1

